/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as BaratRouteImport } from './routes/barat'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WalimaRouteImport } from './routes/walima'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const BaratRoute = BaratRouteImport.update({
  id: '/barat',
  path: '/barat',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WalimaRoute = WalimaRouteImport.update({
  id: '/walima',
  path: '/walima',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/barat': typeof BaratRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/podcast': typeof PodcastRoute
  '/services': typeof ServicesRoute
  '/walima': typeof WalimaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/barat': typeof BaratRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/podcast': typeof PodcastRoute
  '/services': typeof ServicesRoute
  '/walima': typeof WalimaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/barat': typeof BaratRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/podcast': typeof PodcastRoute
  '/services': typeof ServicesRoute
  '/walima': typeof WalimaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/awards'
    | '/barat'
    | '/certificates'
    | '/contact'
    | '/gallery'
    | '/podcast'
    | '/services'
    | '/walima'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/awards'
    | '/barat'
    | '/certificates'
    | '/contact'
    | '/gallery'
    | '/podcast'
    | '/services'
    | '/walima'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/awards'
    | '/barat'
    | '/certificates'
    | '/contact'
    | '/gallery'
    | '/podcast'
    | '/services'
    | '/walima'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AwardsRoute: typeof AwardsRoute
  BaratRoute: typeof BaratRoute
  CertificatesRoute: typeof CertificatesRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PodcastRoute: typeof PodcastRoute
  ServicesRoute: typeof ServicesRoute
  WalimaRoute: typeof WalimaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barat': {
      id: '/barat'
      path: '/barat'
      fullPath: '/barat'
      preLoaderRoute: typeof BaratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walima': {
      id: '/walima'
      path: '/walima'
      fullPath: '/walima'
      preLoaderRoute: typeof WalimaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AwardsRoute: AwardsRoute,
  BaratRoute: BaratRoute,
  CertificatesRoute: CertificatesRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PodcastRoute: PodcastRoute,
  ServicesRoute: ServicesRoute,
  WalimaRoute: WalimaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
