/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/broadcast': typeof BroadcastRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/broadcast': typeof BroadcastRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/broadcast': typeof BroadcastRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/awards' | '/broadcast' | '/contact' | '/podcast'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/awards' | '/broadcast' | '/contact' | '/podcast'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/awards'
    | '/broadcast'
    | '/contact'
    | '/podcast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AwardsRoute: typeof AwardsRoute
  BroadcastRoute: typeof BroadcastRoute
  ContactRoute: typeof ContactRoute
  PodcastRoute: typeof PodcastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AwardsRoute: AwardsRoute,
  BroadcastRoute: BroadcastRoute,
  ContactRoute: ContactRoute,
  PodcastRoute: PodcastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
